### ISSUE TITLE
ValueError: dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by gofly** [alvarolm/GoGuru#21]
Env:

> MaxOSX 10.11.5
> Sublime Text 3 Build 3114

I got error when I press `ctrl+shift+g` and select any function:

``` python
File "goGuru in /Users/zlx/Library/Application Support/Sublime Text 3/Installed Packages/GoGuru.sublime-package", line 210, in guru
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by alvarolm** [comment]
what user settings are you using?

**Comment by gofly** [comment]
My settings of GoGuru is empty, and the full traceback:

``` python
Traceback (most recent call last):
  File "goGuru in /Users/zlx/Library/Application Support/Sublime Text 3/Installed Packages/GoGuru.sublime-package", line 123, in on_done
  File "goGuru in /Users/zlx/Library/Application Support/Sublime Text 3/Installed Packages/GoGuru.sublime-package", line 210, in guru
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by alvarolm** [comment]
@gofly please report the configuration (plugin version, settings) and debug information, will close if not provided

**Comment by alvarolm** [comment]
will close due to lack of information
