### ISSUE TITLE
GOPATH not being detected

### ISSUE THREAD

**Issue by rexposadas** [alvarolm/GoGuru#40]
I have a similar problem as this: https://github.com/alvarolm/GoGuru/issues/19

I have Sublime Text 3 (registered) and GoGuru version 1.1.14
GoGuru (or Sublime) doesn't detect my system $GOPATH and $PATH.

Here is what I see in the console:
```
GoGuru: ('debug:', True)
GoGuru: ('use_golangconfig', False)
GoGuru [DEBUG]: ("couldn't get git tag:", <class 'NotADirectoryError'>)
GoGuru: ('version:', '0.1.14')
Package Control: Skipping automatic upgrade, last run at 2018-03-02 14:17:47, next run at 2018-03-02 15:17:47 or after
environment variables loaded using: /bin/zsh -l
>>> import os;
>>> print (os.environ['PATH'])
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
>>> print (os.environ['GOPATH'])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./python3.3/os.py", line 656, in __getitem__
KeyError: 'GOPATH'
```

In addition to this, the only packages I have installed in my Sublime is GoGuru and Package Installar, just to isolate the problem. 

Any ideas as to why my system $GOPATH and $PATH is not being detected?

In my terminal $GOPATH and $PATH are properly set.

The other thing I tried was setting $GOPATH and $PATH in `goguru_env`, then made a call and got this error: 
`/bin/sh: guru: command not found` . I don't know if it matters, but my default shell is `zsh`.

Thanks in advance for the help.

**Comment by rexposadas** [comment]
I ended up using the `golangconfig` package to set the proper `GOPATH` and `PATH` which fixed the issue for me.
